// Auto-generated by scripts/gen_extension_sets.py

use once_cell::sync::Lazy;
use std::collections::HashSet;
use std::ffi::OsStr;

pub static FONTS: Lazy<HashSet<&'static OsStr>> = Lazy::new(|| {
    let mut set = HashSet::new();
    set.insert(OsStr::new("OTF"));
    set.insert(OsStr::new("OTf"));
    set.insert(OsStr::new("OtF"));
    set.insert(OsStr::new("Otf"));
    set.insert(OsStr::new("oTF"));
    set.insert(OsStr::new("oTf"));
    set.insert(OsStr::new("otF"));
    set.insert(OsStr::new("otf"));
    set.insert(OsStr::new("TTF"));
    set.insert(OsStr::new("TTf"));
    set.insert(OsStr::new("TtF"));
    set.insert(OsStr::new("Ttf"));
    set.insert(OsStr::new("tTF"));
    set.insert(OsStr::new("tTf"));
    set.insert(OsStr::new("ttF"));
    set.insert(OsStr::new("ttf"));
    set
});
