// Auto-generated by scripts/gen_extension_sets.py

use once_cell::sync::Lazy;
use std::collections::HashSet;
use std::ffi::OsStr;

pub static RTM_SUBS: Lazy<HashSet<&'static OsStr>> = Lazy::new(|| {
    let mut set = HashSet::new();
    set.insert(OsStr::new("ASS"));
    set.insert(OsStr::new("ASs"));
    set.insert(OsStr::new("AsS"));
    set.insert(OsStr::new("Ass"));
    set.insert(OsStr::new("aSS"));
    set.insert(OsStr::new("aSs"));
    set.insert(OsStr::new("asS"));
    set.insert(OsStr::new("ass"));
    set.insert(OsStr::new("SRT"));
    set.insert(OsStr::new("SRt"));
    set.insert(OsStr::new("SrT"));
    set.insert(OsStr::new("Srt"));
    set.insert(OsStr::new("sRT"));
    set.insert(OsStr::new("sRt"));
    set.insert(OsStr::new("srT"));
    set.insert(OsStr::new("srt"));
    set
});
